name: Build and publish latest
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm
        run: npm install --no-optional
#      - name: Login to docker hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
            docker build .
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
